# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splitting_criterion_honest_rcpp <- function(split_var_values, X, response, splits) {
    .Call('_HARforest_splitting_criterion_honest_rcpp', PACKAGE = 'HARforest', split_var_values, X, response, splits)
}

splitting_criterion_honest_intercept_only_cpp <- function(split_var_values, response, splits) {
    .Call('_HARforest_splitting_criterion_honest_intercept_only_cpp', PACKAGE = 'HARforest', split_var_values, response, splits)
}

